### ISSUE TITLE
Any plans on supporting dns-01 challenge?

### ISSUE THREAD

**Issue by philkunz** [Daplie/node-letsencrypt#31]
Hi,

letsencrypt now supports dns-01 challenge, which makes obtaining a certificate in CI much simpler. Do you have any plans to implement that?

Regards
Phil

**Comment by coolaj86** [comment]
Would you like to give me the quick run down of what needs to change? Do I need to expose a callback to hand you `keyAuthorization` so that you can set it to a DNS record?

I haven't use the `dns-01` challenge, but I did just add the option for it to letiny-core:

https://github.com/Daplie/letiny-core/pull/8/commits/e7a36123ca4d9d2c72d255fa2ed02acff74ebbf7#diff-8237c7da8c30d998035487db609e6f9dR368

**Comment by coolaj86** [comment]
Let's continue the discussion at https://github.com/Daplie/letiny-core/issues/9

**Comment by coolaj86** [comment]
Check and see if setting `challengeType: 'dns-01'` works for you now in v2.

Check the updated docs: https://github.com/Daplie/node-letsencrypt
