### ISSUE TITLE
Advertisement in readme.

### ISSUE THREAD

**Issue by atmartins** [Daplie/node-letsencrypt#61]
There is a large, irrelevant section in the top of the readme. I am unwilling to use this software due to my perception that it's malware garbage. Be ashamed.

**Comment by coolaj86** [comment]
Well, we passed this through the support team and they can't reproduce your issue. Perhaps it's user error?

Recommendations: Check your pre-conceived notions against facts. Be ashamed.

(sorry, couldn't resist)

**Comment by coolaj86** [comment]
P.S. Our product (a home cloud system secured with https so that people like my mom and dad can have privacy online) is the reason that this repo exists.

All the warm fuzzies in the world won't fill my tummy with oatmeal and bagelwiches on their own. Gotta eat to live. Gotta work to eat. Otherwise we'd all get along.

**Comment by atmartins** [comment]
I steal, only what I can't afford (that's everything!).
