### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by manast** [Daplie/node-letsencrypt#64]
I have been temporarily banned from LE, so I do not know if this error is directly related to it, but anyways, here it comes:
```
Lets encrypt debugger { '0': false,
This Let's Encrypt / ACME server has been updated with urls that this client doesn't understand
{ 'key-change': 'https://acme-v01.api.letsencrypt.org/acme/key-change',
  'new-authz': 'https://acme-v01.api.letsencrypt.org/acme/new-authz',
  'new-cert': 'https://acme-v01.api.letsencrypt.org/acme/new-cert',
  'new-reg': 'https://acme-v01.api.letsencrypt.org/acme/new-reg',
  'revoke-cert': 'https://acme-v01.api.letsencrypt.org/acme/revoke-cert' }
  '1': 'calling le.acme.getCertificateAsync',
  '2': [ 'xxxxxxxxxxxx.com' ] }
```

I am also getting this error directly after the previous one:
```
Lets encrypt debugger { '0': false,
  '1': 'calling le.acme.getCertificateAsync',
  '2': [ 'xxxxxxxxxxxx.com' ] }

Unhandled rejection Error: Failed to get nonce for request
    at Request._callback (/proxy/node_modules/redbird/node_modules/letsencrypt/node_modules/le-acme-core/lib/acme-client.js:46:10)
    at Request.self.callback (/proxy/node_modules/redbird/node_modules/letsencrypt/node_modules/le-acme-core/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/proxy/node_modules/redbird/node_modules/letsencrypt/node_modules/le-acme-core/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/proxy/node_modules/redbird/node_modules/letsencrypt/node_modules/le-acme-core/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any ideas?

**Comment by cpu** [comment]
The `'key-change'` endpoint was added Boulder-side ~last week and has broken some ACME clients that treat unknown `/directory` entries as a hard failure (e.g. See https://github.com/acmephp/acmephp/issues/34).

Ideally `node-letsencrypt` can be updated to treat this as a warning and not a failure. There will be new `/directory` endpoints added over time and well behaving clients should aim to ignore the ones they do not understand.

Hope this helps!

**Comment by insightfuls** [comment]
It is just a warning in `node-letsencrypt`. My certificates renewed a day or two ago, displaying the warning, but with no error, and I verified that the new certificates have installed successfully.

So the problem you are encountering is something else.

Could it be connection-related? I.e. is your server able to access the Let's Encrypt server on port 443?

Apart from that, the only suggestion I have is upgrading or removing configuration files (e.g. in `~/letsencrypt`). I feel like I've seen this error before and it was due to some corrupt or incompatible config files. Try with a recent install of the program and all dependencies, and a clean config directory, and see if it helps.

**Comment by cpu** [comment]
> It is just a warning in node-letsencrypt. My certificates renewed a day or two ago, displaying the warning, but with no error, and I verified that the new certificates have installed successfully.

Ahh! That's ideal then. Ignore me :-)

**Comment by manast** [comment]
hmm, no I think something more serious is actually broken, I deleted the certs directory and this is what I get now:
```
This Let's Encrypt / ACME server has been updated with urls that this client doesn't understand
{ 'key-change': 'https://acme-v01.api.letsencrypt.org/acme/key-change',
  'new-authz': 'https://acme-v01.api.letsencrypt.org/acme/new-authz',
  'new-cert': 'https://acme-v01.api.letsencrypt.org/acme/new-cert',
  'new-reg': 'https://acme-v01.api.letsencrypt.org/acme/new-reg',
  'revoke-cert': 'https://acme-v01.api.letsencrypt.org/acme/revoke-cert' }
/proxy/node_modules/redbird/node_modules/letsencrypt/node_modules/le-acme-core/lib/register-new-account.js:28
        return handleErr(err, 'Registration request failed: ' + res.body.toString('utf8'));
```

Luckily I saved the old certs directory, but my certs expire tomorrow :D, so I am in a bit of a crisis here.

**Comment by manast** [comment]
Also, I have recently started to see this warning, which I have no idea what it means and/or if is related to the error above:
```
le.challenges[http-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'http-01' will succeed
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
Lets encrypt debugger { '0': false, '1': 'created middleware' }
```

**Comment by manast** [comment]
hmm, seems like I am actually in trouble, since the kind of rate limitation that I got (You can have a maximum of 300 Pending Authorizations on your account.), is only cleared after ONE WEEK!
This pending authorization problem seems to be a direct consequence of the error described in my first post :_(

**Comment by insightfuls** [comment]
The `loopback should be defined` is just a warning, too, and not a concern at all. However, IIRC, we recently updated some modules to avoid the warning, at least for `http-01`. The fact that you're seeing it suggests to me that you're not running the most recent versions. What versions of `node-letsencrypt` and related `le-*` modules are you using? In particular, what version is `le-sni-auto`? Especially now that you're so close to expiry, older versions of `le-sni-auto` had a bug where registration attempts were made on every request, which could easily cause you to hit rate limits.

I suspect the error is a result of the rate-limiting, not the other way around. I'm not sure what errors would be logged on renewal failure. It could be that it's ignored because it will probably succeed on the next attempt, which means you'd only find out about the error at the very last moment. Renewals may have been attempted for a while. I guess they'll be failing now due to rate limiting, so there might not be much you can do apart from try to get a certificate some other way, and do what you can to avoid the problem happening again, i.e. update software and check for any other potential problems. E.g. Is your configuration directory (and subdirectories etc.) definitely writable by the server process?

**Comment by jsha** [comment]
@manast I'd recommend that you continue to debug your client using the staging environment, documented at https://letsencrypt.org/docs/staging-environment/, rather than the production environment.

**Comment by jsha** [comment]
Also, checking the logs it looks like your client is still attempting issuance every 4 seconds, which is too frequently. Per the Let's Encrypt [integration guide](https://letsencrypt.org/docs/integration-guide/), your client should automatically back off on failures, eventually retrying at most once per day if it keeps failing.

**Comment by insightfuls** [comment]
I had a quick look at Redbird. It may well be where the bug lies.
- It attempts to renew certificates one month before expiration, and doesn't retry if it fails
- It doesn't configure node-letsencrypt to renew certificates within the same timeframe, so node-letsencrypt will just return a cached certificate one month before
- There is some clarification underway in https://github.com/Daplie/node-letsencrypt/issues/62 which should go a fair distance to helping to resolve this

I don't think `le-sni-auto` is relevant, as Redbird doesn't make use of that. However, Redbird may have a similar bug where it is retrying too often, possibly on every request. Possibly since the certificate didn't renew when it should have due to the misconfiguration, it has got into a panic and is attempting to renew all the time now.

**Comment by manast** [comment]
@insightfuls thanks for all the input. I am working on improvements so that I use the ```renewWithin``` option in the register call. I am still a bit unsure how that is going to work, but I will debug it in the staging environment until I am sure the renewal process works.
